### ISSUE TITLE
MEG - more flexible rules for structural MRI processing

### ISSUE THREAD

**Issue by allermat** [MRC-CBU/BIDS_conversion#10]
Suggested by @RikHenson 
Currently, if `process_structural = True` in `config.py`, all subjects must have their MRI data available and the checks will throw an error. However some participants may not have their structural MRI available with their MEG data. 

Would be better to only check and process structural MRI if `mri_nii_file` and `mri_dcm_dir` are specified in any given subject's subject info. 
This will make the behaviour similar to how emptyroom data are processed. 
This will also make the `process_structural` variable in `config.py` redundant, so I'll remove it.

**Comment by allermat** [comment]
Hi @RikHenson, 

This should be done now. Structural MRI is now converted depending on if `mri_dicom_dir` is specified in the subject_info for each subject. 

To note: 
1. You might have noticed this already, but since the dicom dir is explicitly checked, any leading space (" ") in the file path (ie. " /imaging/...") will now trigger an error. Please remove any leading spaces from these paths in your subject_info.json
2. I simplified further by removing the 'mri_nii_file' field from the subject_info. This was only used for the name of the temporary nifti file in the sourcedata after converting from dicom. I figured I can set this in the code explicitly and not rely on the user.

**Comment by RikHenson** [comment]
I don’t know why, but your latest version didn’t work for missing MRIs or missing empty rooms. I had specified these as “” in subject_info.json, as you had done in your github example. But seeing if these are “not None” failed, so I use “len” instead as below:

#        if info['meg_emptyroom_dir'] is not None:
        if len(info['meg_emptyroom_dir']) > 0 :

Or is something else wrong with my set-up?


---------------------------------------------------------------

Prof Richard Henson, MA, MSc, PhD, FBA
Professor of Cognitive Neuroscience, Department of Psychiatry, University of Cambridge
Director, Cambridge Centre for Ageing and Neuroscience (CamCAN)
President-Past, British Neuroscience Association
Fellow of the British Academy

MRC Cognition and Brain Sciences Unit
University of Cambridge
15 Chaucer Road
Cambridge, CB2 7EF
England
EMAIL:  ***@***.******@***.***>
URL:    http://www.mrc-cbu.cam.ac.uk/people/rik.henson/personal
DIRECT: +44 (0)1223 767 591
RECEPT: +44 (0)1223 355 294
MOBILE: +44 (0)794 1377 345

What is credible neuroscience?<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbnacredibility.org.uk%2F&data=05%7C01%7Caa2175%40universityofcambridgecloud.onmicrosoft.com%7Cf31fcc391c0841ef210808da7eb0ef59%7C49a50445bdfa4b79ade3547b4f3986e9%7C0%7C0%7C637961595642888764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=38s8kijYwDNF2h4ZOSmyFpBI%2BC30eofD350Gg2J4AsE%3D&reserved=0>
---------------------------------------------------------------

**Comment by RikHenson** [comment]
PS I also had to change around line 400:

   #if subject_info['mri_dcm_dir'] is None:
    if len(subject_info['mri_dcm_dir']) == 0:




---------------------------------------------------------------

Prof Richard Henson, MA, MSc, PhD, FBA
Professor of Cognitive Neuroscience, Department of Psychiatry, University of Cambridge
Director, Cambridge Centre for Ageing and Neuroscience (CamCAN)
President-Past, British Neuroscience Association
Fellow of the British Academy

MRC Cognition and Brain Sciences Unit
University of Cambridge
15 Chaucer Road
Cambridge, CB2 7EF
England
EMAIL:  ***@***.******@***.***>
URL:    http://www.mrc-cbu.cam.ac.uk/people/rik.henson/personal
DIRECT: +44 (0)1223 767 591
RECEPT: +44 (0)1223 355 294
MOBILE: +44 (0)794 1377 345

What is credible neuroscience?<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbnacredibility.org.uk%2F&data=05%7C01%7Caa2175%40universityofcambridgecloud.onmicrosoft.com%7Cf31fcc391c0841ef210808da7eb0ef59%7C49a50445bdfa4b79ade3547b4f3986e9%7C0%7C0%7C637961595642888764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=38s8kijYwDNF2h4ZOSmyFpBI%2BC30eofD350Gg2J4AsE%3D&reserved=0>
---------------------------------------------------------------

From: Rik Henson
Sent: 30 April 2024 17:33
To: 'MRC-CBU/BIDS_conversion' ***@***.***>
Cc: Mate Aller ***@***.***>
Subject: RE: [MRC-CBU/BIDS_conversion] MEG - more flexible rules for structural MRI processing (Issue #10)


I don’t know why, but your latest version didn’t work for missing MRIs or missing empty rooms. I had specified these as “” in subject_info.json, as you had done in your github example. But seeing if these are “not None” failed, so I use “len” instead as below:

#        if info['meg_emptyroom_dir'] is not None:
        if len(info['meg_emptyroom_dir']) > 0 :

Or is something else wrong with my set-up?


---------------------------------------------------------------

Prof Richard Henson, MA, MSc, PhD, FBA
Professor of Cognitive Neuroscience, Department of Psychiatry, University of Cambridge
Director, Cambridge Centre for Ageing and Neuroscience (CamCAN)
President-Past, British Neuroscience Association
Fellow of the British Academy

MRC Cognition and Brain Sciences Unit
University of Cambridge
15 Chaucer Road
Cambridge, CB2 7EF
England
EMAIL:  ***@***.******@***.***>
URL:    http://www.mrc-cbu.cam.ac.uk/people/rik.henson/personal
DIRECT: +44 (0)1223 767 591
RECEPT: +44 (0)1223 355 294
MOBILE: +44 (0)794 1377 345

What is credible neuroscience?<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbnacredibility.org.uk%2F&data=05%7C01%7Caa2175%40universityofcambridgecloud.onmicrosoft.com%7Cf31fcc391c0841ef210808da7eb0ef59%7C49a50445bdfa4b79ade3547b4f3986e9%7C0%7C0%7C637961595642888764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=38s8kijYwDNF2h4ZOSmyFpBI%2BC30eofD350Gg2J4AsE%3D&reserved=0>
---------------------------------------------------------------

**Comment by allermat** [comment]
Hi Rik, 

You should specify both of those variable as `null` in the json file. I tried to make this clear in the documentation [here](https://github.com/MRC-CBU/BIDS_conversion/blob/9d2ac9f0aad4debd79f9e140d473eb8c7e6377ce/MEG/README.md?plain=1#L78) and [here](https://github.com/MRC-CBU/BIDS_conversion/blob/9d2ac9f0aad4debd79f9e140d473eb8c7e6377ce/MEG/README.md?plain=1#L86). 

The general approach in the subject_info.json is to use `null` whenever you explicitly don't want to specify something.  After parsing, the fields with `null` value will be set as `None` in the python dictionary. An empty string ("") as you noticed is not `None`, hence the errors. 

I acknowledge, that having a bunch of empty strings in the example subject_info.json does not help. I removed those fields of my original dataset because of PID concerns. I think it would be very useful if we could include a subject_info of an actual dataset where PID is not a concern. So that people at the CBU can actually run the code out of the box and we can avoid these empty strings. I think we've already talked about this in email, do you have a suitable dataset in mind?

**Comment by RikHenson** [comment]
Fine – I can change to “none” - but the example “subject_info.json” on the Github (which I was following) uses empty string for mri_dcm_dir, not null, so you need to update that.

Also, your slurm_meg_bids_conversion_job_script.sh is missing “_data” in the python call – ie needs to be updated to:

python meg_bids_data_conversion.py


---------------------------------------------------------------

Prof Richard Henson, MA, MSc, PhD, FBA
Professor of Cognitive Neuroscience, Department of Psychiatry, University of Cambridge
Director, Cambridge Centre for Ageing and Neuroscience (CamCAN)
President-Past, British Neuroscience Association
Fellow of the British Academy

MRC Cognition and Brain Sciences Unit
University of Cambridge
15 Chaucer Road
Cambridge, CB2 7EF
England
EMAIL:  ***@***.******@***.***>
URL:    http://www.mrc-cbu.cam.ac.uk/people/rik.henson/personal
DIRECT: +44 (0)1223 767 591
RECEPT: +44 (0)1223 355 294
MOBILE: +44 (0)794 1377 345

What is credible neuroscience?<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbnacredibility.org.uk%2F&data=05%7C01%7Caa2175%40universityofcambridgecloud.onmicrosoft.com%7Cf31fcc391c0841ef210808da7eb0ef59%7C49a50445bdfa4b79ade3547b4f3986e9%7C0%7C0%7C637961595642888764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=38s8kijYwDNF2h4ZOSmyFpBI%2BC30eofD350Gg2J4AsE%3D&reserved=0>
---------------------------------------------------------------

**Comment by allermat** [comment]
Thanks, please change it to null (no quotes etc)

I'll change the empty strings in the subject_info to null, but the real solution would be if we could include an actual working dataset here as an example. 

I'll update the slurm script as well, thanks for spotting the error

**Comment by allermat** [comment]
All fixed now.
