### ISSUE TITLE
In MEG, path to MRI wiki not correct

### ISSUE THREAD

**Issue by dcdace** [MRC-CBU/BIDS_conversion#2]
In MEG-Structural MRI section, the path to MRI wiki https://imaging.mrc-cbu.cam.ac.uk/imaging/dicom-bids#Where_are_your_raw_data
does not exist anymore. MRI BIDS was moved from CBU wiki to Github and the correct path to the relevant section is this: https://github.com/MRC-CBU/BIDS_conversion/tree/main/MRI#where-are-your-raw-data

**Comment by allermat** [comment]
Thanks @dcdace for flagging this! Issue is now fixed, closing.
