### ISSUE TITLE
Check if EEG data are present before executing the check_eeg command

### ISSUE THREAD

**Issue by allermat** [MRC-CBU/BIDS_conversion#7]
Flagged by @olafhauk. 
https://github.com/MRC-CBU/BIDS_conversion/blob/b5a365a9ab841717758861fa1a38bcd4e305082f/MEG/meg_bids_data_conversion.py#L183 throws an error when EEG data is not present

Should be easy to check for EEG data, but needs importing every single fif file, which is time consuming. Shall we just add a config option to specify if EEG data are present and execute check_eeg depending on that? What do you think @olafhauk @RikHenson @dcdace?

**Comment by olafhauk** [comment]
I think it should be guaranteed that EEG is fixed whenever present. The raw data are read immediately afterwards in l. 186 - could this be done there?

**Comment by allermat** [comment]
> The raw data are read immediately afterwards in l. 186 - could this be done there?

You're right, we anyway load the raw, so it makes sense to run check_eeg afterwords - depending on if EEG is present or not. 

However, check_eeg will modify the the fif file on disk if EEG channels are present and if there's something to fix so raw would need to be re-loaded after check_eeg is run. This will add extra processing time, but I guess it is not that bad?

**Comment by allermat** [comment]
This should be fixed now. Closing the issue
